const { ROLE_BUNDLES } = require('./role-bundles.config');

const PERMISSION_METADATA = Object.freeze([
  Object.freeze({ code: 'companies.manage', category: 'platform', sensitivity: 'sensitive', scope: 'platform', uiLabel: 'Administrar compañías', notes: 'Solo plataforma' }),
  Object.freeze({ code: 'users.manage', category: 'administration', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Administrar usuarios', notes: 'Capacidad administrativa sensible' }),
  Object.freeze({ code: 'settings.manage', category: 'administration', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Administrar configuración', notes: 'Capacidad administrativa sensible' }),
  Object.freeze({ code: 'clients.manage', category: 'clients', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Gestionar clientes', notes: 'Crear, editar y actualizar clientes' }),
  Object.freeze({ code: 'clients.view', category: 'clients', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver clientes asignados', notes: 'Ver información de clientes asignados sin editar' }),
  Object.freeze({ code: 'clients.view.all', category: 'clients', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver todos los clientes', notes: 'Ver información de todos los clientes comerciales sin editar' }),
  Object.freeze({ code: 'products.manage', category: 'products', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Gestionar artículos', notes: 'Crear y actualizar artículos del catálogo' }),
  Object.freeze({ code: 'products.view', category: 'products', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver artículos', notes: 'Ver artículos del catálogo' }),
  Object.freeze({ code: 'products.import', category: 'products', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Importar artículos', notes: 'Importar artículos desde Excel' }),
  Object.freeze({ code: 'inventory.manage', category: 'inventory', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Gestionar inventario', notes: 'Gestionar bodegas, lotes y movimientos' }),
  Object.freeze({ code: 'inventory.view', category: 'inventory', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver inventario', notes: 'Ver inventario y movimientos' }),
  Object.freeze({ code: 'sales.manage', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Gestionar ventas', notes: 'Gestionar pedidos, facturas y pagos' }),
  Object.freeze({ code: 'sales.orders.create', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Crear pedidos', notes: 'Crear pedidos comerciales' }),
  Object.freeze({ code: 'sales.routes.view.own', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver rutas propias', notes: 'Ver rutas asignadas al agente' }),
  Object.freeze({ code: 'sales.routes.view.all', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver todas las rutas', notes: 'Ver todas las rutas comerciales' }),
  Object.freeze({ code: 'sales.goals.view.own', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver metas propias', notes: 'Ver metas propias del agente' }),
  Object.freeze({ code: 'sales.goals.view.all', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver todas las metas', notes: 'Ver metas de todos los agentes' }),
  Object.freeze({ code: 'customer.activities.manage', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Registrar actividades comerciales', notes: 'Registrar visitas, gestiones y seguimiento comercial' }),
  Object.freeze({ code: 'customer.activities.view.all', category: 'sales', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver actividades del equipo', notes: 'Ver actividades comerciales de todo el equipo' }),
  Object.freeze({ code: 'collections.manage.own', category: 'collections', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Registrar cobros propios', notes: 'Registrar cobros propios del agente' }),
  Object.freeze({ code: 'collections.view.all', category: 'collections', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver cobros del equipo', notes: 'Ver cobros del equipo comercial' }),
  Object.freeze({ code: 'inventory.qa.manage', category: 'inventory', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Gestionar QA de inventario', notes: 'Capacidad excepcional de inventario' }),
  Object.freeze({ code: 'inventory.approve', category: 'inventory', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Aprobar inventario', notes: 'Capacidad excepcional de inventario' }),
  Object.freeze({ code: 'warehouse.access', category: 'warehouse', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Acceder al espacio operativo de bodega', notes: 'Acceso base al SPA operativo de bodega/QA' }),
  Object.freeze({ code: 'warehouse.receive', category: 'warehouse', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ejecutar recepciones de bodega', notes: 'Habilita las pestañas de Recepciones e Inventario en el SPA operativo de bodega' }),
  Object.freeze({ code: 'products.sourcing.view', category: 'supply', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver clasificación de abastecimiento', notes: 'Consulta de sourcing e inventario del producto' }),
  Object.freeze({ code: 'products.sourcing.manage', category: 'supply', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Gestionar clasificación de abastecimiento', notes: 'Configura sourcing, costos, bodegas y metadatos físicos del producto' }),
  Object.freeze({ code: 'suppliers.view', category: 'procurement', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver proveedores autorizados', notes: 'Consulta catálogo y autorizaciones de proveedores' }),
  Object.freeze({ code: 'suppliers.manage', category: 'procurement', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Gestionar proveedores autorizados', notes: 'Administra proveedores y autorizaciones por producto' }),
  Object.freeze({ code: 'recipes.view', category: 'production', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver recetas y versiones', notes: 'Consulta administrativa de recetas' }),
  Object.freeze({ code: 'recipes.operations.view', category: 'production', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Consultar fórmulas operativas congeladas', notes: 'Solo consulta operacional de la receta/version congelada en órdenes de producción' }),
  Object.freeze({ code: 'recipes.manage', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Gestionar recetas y versiones', notes: 'Crea y edita recetas y borradores de versión' }),
  Object.freeze({ code: 'recipes.approve', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Aprobar versiones de receta', notes: 'Aprueba versiones inmutables de receta' }),
  Object.freeze({ code: 'production.view', category: 'production', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver órdenes de producción', notes: 'Consulta y seguimiento de órdenes de producción' }),
  Object.freeze({ code: 'production.create', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Crear órdenes de producción', notes: 'Crea y envía órdenes de producción' }),
  Object.freeze({ code: 'production.approve', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Aprobar órdenes de producción', notes: 'Aprueba órdenes antes de ejecución' }),
  Object.freeze({ code: 'production.execute', category: 'production', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ejecutar producción', notes: 'Registra etapas, consumos y evidencias de producción' }),
  Object.freeze({ code: 'production.complete', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Completar producción', notes: 'Cierra producción y habilita la entrada por producción' }),
  Object.freeze({ code: 'production.cancel', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Cancelar producción', notes: 'Cancela órdenes de producción' }),
  Object.freeze({ code: 'production.override', category: 'production', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Sobrescribir guardas de producción', notes: 'Permite producir sin receta/sourcing válido solo con justificación', requiresJustification: true }),
  Object.freeze({ code: 'quality.view', category: 'quality', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver inspecciones QA', notes: 'Consulta inspecciones QA de producción y recepción' }),
  Object.freeze({ code: 'quality.inspect', category: 'quality', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Registrar inspecciones QA', notes: 'Registra resultados QA y evidencia' }),
  Object.freeze({ code: 'quality.override', category: 'quality', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Sobrescribir bloqueo QA', notes: 'Permite acciones excepcionales sobre bloqueos QA con justificación', requiresJustification: true }),
  Object.freeze({ code: 'procurement.view', category: 'procurement', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver abastecimiento', notes: 'Consulta solicitudes, cotizaciones y órdenes de compra' }),
  Object.freeze({ code: 'procurement.manage', category: 'procurement', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Gestionar abastecimiento', notes: 'Gestiona solicitudes, cotizaciones, comparativos y órdenes de compra' }),
  Object.freeze({ code: 'procurement.approve', category: 'procurement', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Aprobar selección de proveedor', notes: 'Aprueba selección/proceso de compra según umbrales' }),
  Object.freeze({ code: 'procurement.override', category: 'procurement', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Sobrescribir guardas de compra', notes: 'Permite comprar sin proveedor autorizado solo con justificación', requiresJustification: true }),
  Object.freeze({ code: 'receipts.view', category: 'warehouse', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver recepciones', notes: 'Consulta documentos de recepción y su estado' }),
  Object.freeze({ code: 'receipts.inspect', category: 'warehouse', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Inspeccionar recepciones', notes: 'Inspecciona cantidades, calidad y evidencia en recepción' }),
  Object.freeze({ code: 'receipts.confirm', category: 'warehouse', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Confirmar recepciones', notes: 'Confirma entradas físicas al inventario' }),
  Object.freeze({ code: 'receipts.reverse', category: 'warehouse', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Revertir recepciones', notes: 'Revierte entradas confirmadas con historial controlado' }),
  Object.freeze({ code: 'inventory.intake.override', category: 'inventory', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Sobrescribir validaciones de entrada', notes: 'Acción excepcional sobre validaciones de entrada con justificación', requiresJustification: true }),
  Object.freeze({ code: 'billing.handoff.view', category: 'billing-boundary', sensitivity: 'operational', scope: 'tenant', uiLabel: 'Ver handoff fiscal', notes: 'Consulta referencias y estado de handoff a Billing' }),
  Object.freeze({ code: 'billing.handoff.create', category: 'billing-boundary', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Crear handoff fiscal', notes: 'Registra referencias pendientes hacia Billing/Hacienda' }),
  Object.freeze({ code: 'sales.routes.assign', category: 'sales', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Asignar rutas', notes: 'Capacidad de coordinación operativa' }),
  Object.freeze({ code: 'sales.goals.assign', category: 'sales', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Asignar metas', notes: 'Capacidad de coordinación operativa' }),
  Object.freeze({ code: 'collections.assign', category: 'collections', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Asignar cobranza', notes: 'Capacidad de coordinación operativa' }),
  Object.freeze({ code: 'collections.payments.approve', category: 'collections', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Aprobar pagos', notes: 'Capacidad financiera sensible' }),
  Object.freeze({ code: 'collections.payments.reverse', category: 'collections', sensitivity: 'sensitive', scope: 'tenant', uiLabel: 'Revertir pagos', notes: 'Capacidad financiera sensible' }),
]);

const GOVERNED_OPERATIONS = Object.freeze([
  Object.freeze({ operation: 'company.create', phase: 'first-stable-deny', enforcement: 'deny', status: 'approved' }),
  Object.freeze({ operation: 'role.company.create', phase: 'warning-foundation', enforcement: 'warn', status: 'proposed' }),
  Object.freeze({ operation: 'role.company.update', phase: 'warning-foundation', enforcement: 'warn', status: 'proposed' }),
  Object.freeze({ operation: 'permission-guided-view', phase: 'ui-guidance', enforcement: 'warn', status: 'proposed' }),
  Object.freeze({ operation: 'production.override', phase: 'permission-foundation', enforcement: 'approved', status: 'approved' }),
  Object.freeze({ operation: 'procurement.override', phase: 'permission-foundation', enforcement: 'approved', status: 'approved' }),
  Object.freeze({ operation: 'quality.override', phase: 'permission-foundation', enforcement: 'approved', status: 'approved' }),
  Object.freeze({ operation: 'inventory.intake.override', phase: 'permission-foundation', enforcement: 'approved', status: 'approved' }),
]);

const COMBINATION_RULES = Object.freeze([
  Object.freeze({
    ruleId: 'platform-root-only-company-create',
    description: 'Solo root global puede crear compañías nuevas',
    severity: 'deny',
    appliesTo: Object.freeze(['company.create']),
    status: 'approved',
  }),
  Object.freeze({
    ruleId: 'tenant-role-platform-permission-denied',
    description: 'Los roles de empresa no pueden incluir permisos de alcance plataforma',
    severity: 'deny',
    appliesTo: Object.freeze(['role.company.create', 'role.company.update']),
    status: 'approved',
    restrictedScope: 'platform',
  }),
]);

const WARNING_CONTRACT_FIELDS = Object.freeze([
  'code',
  'ruleId',
  'message',
  'severity',
  'affectedPermissions',
  'status',
]);

const PERMISSION_GOVERNANCE_POLICY = Object.freeze({
  version: 1,
  bundles: ROLE_BUNDLES,
  permissionMetadata: PERMISSION_METADATA,
  governedOperations: GOVERNED_OPERATIONS,
  combinationRules: COMBINATION_RULES,
  warningContractFields: WARNING_CONTRACT_FIELDS,
});

module.exports = {
  PERMISSION_GOVERNANCE_POLICY,
  PERMISSION_METADATA,
  GOVERNED_OPERATIONS,
  COMBINATION_RULES,
  WARNING_CONTRACT_FIELDS,
};
